version: '2.2'

volumes:
  couchbase-data:

services:

  Apache_Shib:
    image: ubuntu_shib
    container_name: ubuntu_shib
    build: .
    environment:
##      ####### APACHE SECTION #######
      - SERVICE_TO_PROTECT=tomcat
      - SERVICE_PORT=8080
##      ####### SHIBBOLETH SECTION #######
      - HOSTNAME=${DNS_NAME}
      - IDP_ENTITY_ID=${IDP_ENTITY_ID}
      - IDP_METADATA_URL=${IDP_METADATA_URL}
    ports:
      - 80:80
      - 443:443
